[package]
name = "codlab"
version = "0.1.0"
edition = "2024"

[dependencies]
async-lsp = { version = "0.2.2", features = ["async-io", "tokio"] }
futures = "0.3.31"
tokio = { version = "1.44.1", features = ["macros", "rt", "time"] }
tower = "0.5.2"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
