name: Run nix tests

on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        name: codlab
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
        enable_kvm: true
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix develop -c just ci
