name: Run nix tests

on:
  pull_request:
  push:

jobs:
  nix-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v31
      with:
        name: codlab
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        extraPullNames: nix-community
        enable_kvm: true
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: nix develop -c just ci
    - uses: actions/upload-artifact@v4
      with:
        name: video-recordings
        path: ci-output
        if-no-files-found: error
        # videos are already compressed
        compression-level: 0
